name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-action@v2
        with:
          command: install

      - name: Render Quarto site
        uses: quarto-dev/quarto-action@v2
        with:
          command: render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
